# Generated by Django 5.2.4 on 2025-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_rename_vote_averate_movie_vote_average"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.TextField(blank=True, null=True),
        ),
    ]
